### ISSUE TITLE
PR Template.

### ISSUE THREAD

**Issue by kareraolivier** [manzitresor/team4-website-project-real#3]
- [ ] Create a pull request template. 
- [ ] And share it with the coach so that It can get merged quickly so that you can use it on pr.

**Comment by manzitresor** [comment]
Dear @kareraolivier  

Thank for the feedback and we have implemented PR template.
Here is the link: [https://github.com/manzitresor/team4-website-project-real/blob/dev/.github/pull_request_template.md](url)
